name: Build and Deploy HomePage
on:
 push:
  branches:
    - master
  paths-ignore:
    - '.github/**'
    - 'README.md'
 pull_request:
  branches:
    - master
  paths-ignore:
    - '.github/**'
    - 'README.md'
# on:
#   workflow_dispatch:
# on:
#   watch:
#     types: started
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2.4.0
    with:
     persist-credentials: false
     node-version: 15.9.0
  - name: Install and Build ⚙️
    run: |
     npm install
     npm run-script build
  - name: Deploy github Page 🚀
    uses: JamesIves/github-pages-deploy-action@4.1.8
    with:
     BRANCH: gh-pages # 存放产物的分支名称
     FOLDER: dist # 存放build后产物的目录
  - name: show my IP
    run: |
     curl ifconfig.me
  - name: Deploy to Server
    uses: easingthemes/ssh-deploy@main
    env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/node_modules/"
